#
# Copyright contributors to the Galasa project 
#
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: inttests-repo-build
  namespace: galasa-tekton
spec:
  workspaces:
  - name: git-workspace
    optional: false
  params:
  - name: distBranch
    type: string
  - name: refspec
    type: string
  - name: noPush
    type: string
    default: ""
  - name: bootstrap
    type: string
    default: "http://galasa-cicsk8s.hursley.ibm.com/bootstrap"
  - name: skipTestCatalog
    type: string
    default: "true"
  tasks:
  - name: clone-inttests
    taskRef: 
      name: git-clone
    params:
    - name: url
      value: https://github.com/galasa-dev/integratedtests
    - name: revision
      value: $(params.distBranch)
    - name: refspec
      value: $(params.refspec)
    - name: depth
      value: "99999999"
    - name: subdirectory
      value: inttests
    workspaces:
     - name: output
       workspace: git-workspace
  - name: inttests-compile
    taskRef:
      name: inttests-repo-build
    runAfter:
    - clone-inttests
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: managersSourceRepo
      value: https://galasadev-cicsk8s.hursley.ibm.com/$(params.distBranch)/maven/managers/
    - name: noPush
      value: $(params.noPush)
    - name: bootstrap
      value: $(params.bootstrap)
    - name: skipTestCatalog
      value: $(params.skipTestCatalog)
    workspaces:
     - name: git-workspace
       workspace: git-workspace
  - name: recycle-inttests
    taskRef:
      name: recycle-deployment
    runAfter:
    - inttests-compile
    when:
    - input: "$(params.noPush)"
      operator: notin
      values: ["--no-push"]
    params:
    - name: namespace
      value: galasa-branch-main
    - name: deployment
      value: maven-$(params.distBranch)-inttests
