#
# Copyright contributors to the Galasa project 
#
kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  generateName: main-inttests-
  namespace: galasa-tekton
spec:
  params:
  - name: distBranch
    value: main
  - name: refspec
    value: +refs/heads/main:refs/heads/main
  pipelineRef:
    name: inttests-repo-build
  serviceAccountName: build-bot
  podTemplate:
    nodeSelector:
      kubernetes.io/arch: amd64
  workspaces:
  - name: git-workspace
    volumeClaimTemplate:
      spec:
        storageClassName: longhorn-temp
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
