#
# Copyright contributors to the Galasa project 
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-inttests
  labels:
    app: maven-inttests
spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: maven-inttests
  template:
    metadata:
      labels:
        app: maven-inttests
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: maven-inttests
        image: {{ .Values.registry }}/galasadev/galasa-maven-inttests:{{ .Values.branch }}
        imagePullPolicy: Always
        env:
        - name: CONTEXTROOT
          value: {{ .Values.branch }}/maven/inttests 
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources:
          requests:
            memory: 50Mi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - maven-inttests
              topologyKey: kubernetes.io/hostname
